# Generated by Django 3.1.4 on 2020-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topback',
            name='document',
            field=models.FileField(blank=True, max_length=120, null=True, upload_to='documents/'),
        ),
    ]
