# Generated by Django 3.1.4 on 2021-01-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_topback_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topback',
            name='document',
        ),
        migrations.AddField(
            model_name='topback',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topback',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telephone'),
        ),
    ]
