# Generated by Django 3.1.4 on 2021-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210105_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topback',
            name='cover',
        ),
        migrations.AddField(
            model_name='topback',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
