# Generated by Django 3.1.4 on 2021-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210105_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topback',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
