# Generated by Django 3.1.4 on 2021-01-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210115_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topback',
            name='document',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
