# Generated by Django 3.1.4 on 2021-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_auto_20210201_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(),
        ),
    ]
