# Generated by Django 3.1.4 on 2021-02-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0004_auto_20210203_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text1',
            field=models.TextField(null=True, verbose_name='Текст1'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text2',
            field=models.TextField(null=True, verbose_name='Текст2'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text3',
            field=models.TextField(null=True, verbose_name='Текст3'),
        ),
    ]
