# Generated by Django 3.1.4 on 2021-02-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0005_auto_20210203_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Текст1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Текст2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Текст3'),
        ),
    ]
