# Generated by Django 3.1.4 on 2021-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0006_auto_20210203_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Photo2'),
        ),
    ]
